## Вычисления с помощью Numpy

### Задание 1

In [1]:
import numpy as np

In [11]:
b = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]])

In [12]:
a = b.T

In [13]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [14]:
mean_a = a.mean(axis = 0)

In [15]:
mean_a

array([2. , 8.4])

### Задание 2

In [18]:
a_centered = a - mean_a

In [19]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [32]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]

In [33]:
a_centered_sp

8.0

In [43]:
a_centered_sp / (a.T[0].size - 1)

2.0

### Задание 4

In [44]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

## Работа с данными в Pandas

### Задание 1

In [3]:
import pandas as pd

In [4]:
authors = pd.DataFrame({'author_id':[1, 2, 3], 'author_name':['Тургенев', 'Чехов', 'Островский']}, columns = ['author_id', 'author_name'])


In [5]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [6]:
a_id = [1, 1, 1, 2, 2, 3, 3]

In [9]:
b_title = ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']

In [10]:
price = [450, 300, 350, 500, 450, 370, 290]

In [11]:
book = pd.DataFrame({'author_id':a_id, 'book_title':b_title, 'price': price}, columns = ['author_id', 'book_title', 'price'])

In [12]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

In [13]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner')

In [14]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3

In [15]:
top5 = authors_price.nlargest(5, 'price')

In [16]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

In [37]:
authors_stat = authors_price.groupby('author_name').price.agg(['min', 'max', 'mean'])  

In [38]:
authors_stat

min  max        mean
author_name                      
Островский   290  370  330.000000
Тургенев     300  450  366.666667
Чехов        450  500  475.000000

In [39]:
authors_stat = authors_stat.rename(columns = {'max' : 'max_price', 'min' : 'min_price', 'mean' : 'mean_price'})

In [40]:
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

### Задание 5**

In [41]:
df2 = pd.DataFrame(pd.Series(['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']))

In [56]:
df2 = df2.rename(columns = {0 : 'cover_type'})

In [57]:
df2

cover_type
0    твердая
1     мягкая
2     мягкая
3    твердая
4    твердая
5     мягкая
6     мягкая

In [63]:
authors_price = pd.concat([authors_price, df2], axis = 1, ignore_index = True)

In [64]:
authors_price

0           1                     2    3        4
0  1    Тургенев           Отцы и дети  450  твердая
1  1    Тургенев                 Рудин  300   мягкая
2  1    Тургенев     Дворянское гнездо  350   мягкая
3  2       Чехов      Толстый и тонкий  500  твердая
4  2       Чехов       Дама с собачкой  450  твердая
5  3  Островский                 Гроза  370   мягкая
6  3  Островский  Таланты и поклонники  290   мягкая

In [46]:
pd.pivot_table?

In [65]:
book_info = pd.pivot_table(authors_price, 3, index=1, columns=4, aggfunc = 'sum', fill_value = 0)


In [66]:
book_info

4           мягкая  твердая
1                          
Островский     660        0
Тургенев       650      450
Чехов            0      950

In [67]:
book_info.to_pickle('book_info.pkl')


In [68]:
book_info2 = pd.read_pickle('book_info.pkl')

In [69]:
book_info2

4           мягкая  твердая
1                          
Островский     660        0
Тургенев       650      450
Чехов            0      950